// Restaurant and menu data are kept together here for straightforward updates.
const restaurant={name:'Akshar Pure Veg Restaurant',phone:'+974 7000 4637',whatsapp:'97470004637',email:'akshar.qatar@gmail.com',location:'Al Wukair, Qatar',hours:'11:00 AM – 11:00 PM',hoursConfirmed:false,designer:'Aayush'};
const whatsapp=(message='Hello Akshar Restaurant, I would like to place an order.')=>'https://wa.me/'+restaurant.whatsapp+'?text='+encodeURIComponent(message);
document.querySelectorAll('.wa-link').forEach(a=>{a.href=whatsapp();a.target='_blank';a.rel='noopener'});
document.querySelector('#nav-toggle').addEventListener('click',e=>{const open=document.querySelector('#nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open);e.currentTarget.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
window.addEventListener('scroll',()=>document.querySelector('header').classList.toggle('scrolled',scrollY>20),{passive:true});
const categories=['Street Food','Starters','North Indian','South Indian','Gujarati Specialities','Rice & Biryani','Breads','Desserts','Drinks'];
const dishes=[
 {name:'Paneer Tikka',category:'Starters',description:'Chargrilled paneer, aromatic spices and a beautifully smoky finish.',image:'paneer',price:null,favourite:true},
 {name:'Pani Puri',category:'Street Food',description:'Crisp puris, spiced potatoes and tangy mint water. A little burst of joy.',image:'puri',price:null,favourite:true},
 {name:'Pav Bhaji',category:'Street Food',description:'Slow-cooked vegetable bhaji with soft, buttery toasted pav.',image:'pav',price:null,favourite:true},
 {name:'Chole Bhature',category:'North Indian',description:'Spiced chickpeas paired with golden, fluffy bhature.',image:'chole',price:null,favourite:true},
 {name:'Masala Dosa',category:'South Indian',description:'A golden, crisp dosa filled with gently spiced potatoes.',image:'dosa',price:null,favourite:true},
 {name:'Veg Biryani',category:'Rice & Biryani',description:'Fragrant basmati rice layered with vegetables and warming spices.',image:'biryani',price:null,favourite:true},
 {name:'Gujarati Thali',category:'Gujarati Specialities',description:'A comforting selection of Gujarati flavours, served together.',image:'thali',price:null,favourite:true},
 {name:'North Indian Thali',category:'North Indian',description:'A generous collection of curries, dal, rice and Indian bread.',image:'north',price:null,favourite:true},
 {name:'Butter Naan',category:'Breads',description:'Soft Indian flatbread finished with butter. Perfect for your favourite curry.',price:null},
 {name:'Gulab Jamun',category:'Desserts',description:'Soft golden dumplings soaked in a delicately fragrant sugar syrup.',image:'dessert',price:null},
 {name:'Masala Chai',category:'Drinks',description:'Comforting Indian tea brewed with milk and aromatic spices.',price:null},
 {name:'Sweet Lassi',category:'Drinks',description:'A cool, creamy yoghurt drink with a touch of sweetness.',price:null}
];
const maps='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(restaurant.name+' '+restaurant.location);
const veg='<span class="veg" aria-label="Vegetarian">●</span>';
function dishCard(d){return `<article class="dish-card">${d.image?`<div class="dish-photo"><img src="images/${d.image}.webp" alt="${d.name}, representative dish photograph" loading="lazy" width="500" height="350">${veg}</div>`:''}<div class="dish-info"><h3>${d.name} ${!d.image?veg:''}</h3><p>${d.description}</p><div class="dish-bottom"><span>${d.price===null?'QAR — <span class="sr-only">Price to be confirmed</span>':'QAR '+d.price}</span><a class="order-link" target="_blank" rel="noopener" href="${whatsapp('Hello Akshar Restaurant, I would like to order '+d.name+'. Please confirm availability and price.')}" aria-label="Order ${d.name} on WhatsApp">Order ↗</a></div></div></article>`}
const gallery=[{image:'thali',label:'A table full of Indian flavours'},{image:'interior',label:'Warm dining spaces · inspiration'},{image:'paneer',label:'A closer look at paneer tikka'},{image:'puri',label:'The joy of Indian street food'},{image:'dessert',label:'Something sweet to finish'},{image:'interior',label:'Gather around the table · inspiration'}];
const highlights=[['♧','100% Vegetarian','A celebration of vegetables, pulses, grains and the pleasure of pure vegetarian food.'],['✧','Traditional Indian Flavours','Recipes shaped by the spices and regional traditions of India.'],['♡','Family Friendly','A welcoming setting to slow down, share a meal and spend time together.'],['◷','Freshly Prepared','Care in the kitchen, from the first ingredient to the final garnish.'],['❋','Quality Ingredients','Good food begins with carefully chosen ingredients.'],['⌖','Convenient Qatar Location','Find us in Al Wukair, ready to welcome you to the table.']];
document.querySelector('#home-content').innerHTML=`
 <section class="section two-col" id="about"><div class="about-picture"><img src="images/north.webp" alt="An Indian vegetarian thali with a variety of curries, bread and rice" loading="lazy" width="650" height="700"><div class="picture-label">Rooted in India. Served with love.</div></div><div class="about-copy"><p class="eyebrow">OUR TABLE, YOUR HOME</p><h2>A Taste of India<br>in Qatar</h2><p>Akshar Pure Veg Restaurant brings the flavours of Indian vegetarian cuisine to Qatar. Our dishes celebrate traditional recipes, aromatic spices and freshly prepared ingredients while offering a comfortable dining experience for families and food lovers.</p><p>From a quick bite of street food to a leisurely thali, there is always a little taste of home waiting for you.</p><a class="text-link" href="#story">Our Story <span>↗</span></a></div></section>
 <section class="section favourites" id="favourites"><div class="section-heading"><div><p class="eyebrow">GOOD FOOD. HAPPY HEARTS.</p><h2>Our Favourites</h2><p>A little comfort. A little spice. A lot to love.</p></div><a class="text-link" href="#menu">View Full Menu <span>↗</span></a></div><div class="dish-grid">${dishes.filter(d=>d.favourite).map(dishCard).join('')}</div><p class="section-note">Illustrative menu · dishes and prices to be confirmed. Ask us on WhatsApp for today’s availability.</p></section>
 <section class="section flavour" id="story"><p class="eyebrow">THE HEART OF AKSHAR</p><h2>From India, <em>With Flavour.</em></h2><div class="values"><article class="value"><div class="value-icon">✧</div><h3>Authentic Recipes</h3><p>Regional favourites, familiar spices and recipes that carry the warmth of Indian home cooking.</p></article><article class="value"><div class="value-icon">❋</div><h3>Freshly Prepared</h3><p>Chopped, stirred, seasoned and served with care. Because the little details make every meal special.</p></article><article class="value"><div class="value-icon">♧</div><h3>Pure Vegetarian</h3><p>A whole world of flavour, entirely vegetarian. Food that brings everyone around the same table.</p></article></div></section>
 <section class="section"><div class="section-heading"><div><p class="eyebrow">MAKE YOURSELF AT HOME</p><h2>Why Choose Akshar?</h2></div></div><div class="why-grid">${highlights.map(([i,t,d])=>`<article class="why-item"><span aria-hidden="true">${i}</span><div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div></section>
 <section class="section" id="gallery"><div class="section-heading"><div><p class="eyebrow">A FEAST FOR THE EYES</p><h2>A Little Taste of Akshar</h2></div><p>Food, flavour & moments around the table.</p></div><div class="gallery-grid">${gallery.map((g,i)=>`<button class="gallery-item" data-gallery="${i}" aria-label="Enlarge ${g.label}"><img src="images/${g.image}.webp" alt="${g.label}" loading="lazy" width="700" height="600"><span>${g.label} <b aria-hidden="true">↗</b></span></button>`).join('')}</div><p class="section-note">Representative food photography and dining inspiration; these are not photographs of the Akshar venue.</p></section>
 <section class="section reviews"><div class="center"><p class="eyebrow">AROUND OUR TABLE</p><h2>What Our Guests Say</h2><p class="section-note">Sample reviews for design preview — not verified customer testimonials.</p></div><div class="review-grid">${[['“The kind of comforting vegetarian meal that makes you slow down and savour every bite.”','A family meal'],['“From the tangy street food to a generous thali, there is something for every craving.”','A taste of home'],['“A lovely place to imagine sharing good food, good conversation and another cup of chai.”','Time together']].map(([q,n])=>`<article class="review"><div class="quote" aria-hidden="true">“</div><blockquote>${q.replace(/[“”]/g,'')}</blockquote><footer>${n}</footer><small>Illustrative review · replace before public launch</small></article>`).join('')}</div></section>
 <section class="cta"><p class="eyebrow light" style="justify-content:center">YOUR NEXT FAVOURITE MEAL AWAITS</p><h2>Craving Authentic Indian<br>Vegetarian Food?</h2><p>Visit Akshar or order your favourites today.</p><div class="hero-buttons"><a class="button gold" href="#menu">View Menu ↗</a><a class="button outline" href="${whatsapp()}" target="_blank" rel="noopener">◉ &nbsp; Order on WhatsApp</a></div></section>
 <section class="section" id="contact"><p class="eyebrow">WE’LL SAVE YOU A WARM WELCOME</p><h2>Visit Akshar</h2><div class="contact-layout"><div><h3>Akshar Pure Veg Restaurant – Qatar</h3><p>${restaurant.location}</p><div class="contact-links"><a href="tel:${restaurant.phone.replaceAll(' ','')}">☎ &nbsp; ${restaurant.phone}</a><a href="${whatsapp()}" target="_blank" rel="noopener">◉ &nbsp; WhatsApp: ${restaurant.phone}</a><a href="mailto:${restaurant.email}">✉ &nbsp; ${restaurant.email}</a></div><div class="contact-actions"><a class="button small" href="tel:${restaurant.phone.replaceAll(' ','')}">Call Us</a><a class="button small" href="${whatsapp()}" target="_blank" rel="noopener">WhatsApp</a><a class="text-link" href="${maps}" target="_blank" rel="noopener">Google Maps ↗</a></div><div class="hours"><h3>Opening Hours</h3><div class="hours-row"><span>Monday – Sunday</span><span>${restaurant.hours}</span></div><p>${restaurant.hoursConfirmed?'':'Sample hours · please call to confirm before visiting.'}</p></div></div><form class="form-card" id="contact-form"><h3>Say hello</h3><p>Have a question? Your message will open in your email app, ready to send.</p><div class="form-grid"><label>Name<input name="name" autocomplete="name" required maxlength="100"></label><label>Phone<input name="phone" type="tel" autocomplete="tel" maxlength="35"></label><label class="full">Email<input name="email" type="email" autocomplete="email" required maxlength="180"></label><label class="full">Message<textarea name="message" required maxlength="3000" rows="3"></textarea></label></div><button class="button" type="submit">Send Message <span>↗</span></button><p id="form-status" role="status" style="margin:12px 0 0"></p></form></div><div class="map-placeholder" aria-label="Map placeholder for Al Wukair Qatar"><div><strong>⌖ Al Wukair, Qatar</strong><p>Map placeholder · exact restaurant pin to be confirmed.</p><a class="button small" href="${maps}" target="_blank" rel="noopener">Find Akshar on Google Maps ↗</a></div></div></section>`;
const credits=[['Gujrati_Thali.jpg','Bheem3'],['Paneer_tikka_1.jpg','Srikoundinya66'],['Pani_Puri_-_Perfect_Street_food.JPG','Zeel Patel'],['Pavbhaji.jpg','Monali.mishra'],['Chole_Bhature_-_North_India.jpg','Avinashvh1n1'],['A_plate_of_South_Indian_Masala_Dosa.jpg','Billjones94'],['Vegetable_biryani_special.jpg','Dhivya Bharathi Official'],['North_Indian_Veg_Thali.jpg','Asif Saleh']];
document.querySelector('#footer-content').innerHTML=`<footer class="site-footer"><div class="footer-grid"><div><a class="brand" href="#home"><span class="brand-icon">a<span>✦</span></span><span><strong>akshar</strong><small>PURE VEG RESTAURANT</small></span></a><p>Authentic Pure Vegetarian Indian Food in Qatar. Familiar flavours, fresh ingredients and a warm welcome at every table.</p><div class="social-links"><a href="${whatsapp()}" target="_blank" rel="noopener" aria-label="Connect on WhatsApp">◉</a><a href="mailto:${restaurant.email}" aria-label="Email Akshar">✉</a><a href="${maps}" target="_blank" rel="noopener" aria-label="Find us on Google Maps">⌖</a></div></div><div><h3>Explore Akshar</h3><div class="footer-links"><a href="#menu">Menu</a><a href="#about">About Us</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></div></div><div><h3>Come Say Hello</h3><div class="footer-links"><span>${restaurant.location}</span><a href="tel:${restaurant.phone.replaceAll(' ','')}">${restaurant.phone}</a><a href="${whatsapp()}" target="_blank" rel="noopener">Order on WhatsApp ↗</a><a href="mailto:${restaurant.email}">${restaurant.email}</a></div></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Akshar Pure Veg Restaurant. All rights reserved.</span>${restaurant.designer?`<span>Website designed by ${restaurant.designer}</span>`:''}</div><details class="photo-credits"><summary>Photography credits</summary><p>Images are representative, resized and cropped for layout. ${credits.map(([file,author])=>`<a href="https://commons.wikimedia.org/wiki/File:${file}" target="_blank" rel="noopener">${file.replaceAll('_',' ')} — ${author}</a>`).join('; ')}. Food images above: <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a> (including cropped versions). <a href="https://commons.wikimedia.org/wiki/File:Golab_Jamun.jpg" target="_blank" rel="noopener">Gulab jamun — Apurv013, CC0</a>. Interior: <a href="https://unsplash.com/photos/a-restaurant-filled-with-wooden-tables-and-chairs-jHyxPnJTvIQ" target="_blank" rel="noopener">Cody Chan / Unsplash</a>.</p></details></footer>`;
document.querySelector('#menu-view').innerHTML=`<div class="menu-banner"><p class="eyebrow">A JOURNEY THROUGH INDIA</p><h1>Something for Every Craving.</h1><p>From crisp dosas to comforting thalis. Explore our pure vegetarian favourites, one delicious dish at a time.</p><p class="section-note" style="margin-top:15px">Illustrative menu · all dishes and prices await confirmation.</p></div><div class="menu-controls"><div class="search-wrap"><label class="sr-only" for="menu-search">Search menu items</label><input id="menu-search" type="search" placeholder="Search for a dish or ingredient…" autocomplete="off"></div><div class="categories" role="group" aria-label="Filter menu by category">${['All',...categories].map(c=>`<button class="category" aria-pressed="${c==='All'}" data-category="${c}">${c}</button>`).join('')}</div></div><div class="menu-results"><p class="results-label" id="results-label" role="status" aria-live="polite"></p><div id="menu-grid" class="dish-grid"></div><div class="empty-result" id="empty-result" hidden><h3>No dishes found</h3><p>Try another search, or explore all our categories.</p><button class="button" id="reset-search">Clear filters</button></div><p class="section-note">QAR — indicates a price awaiting confirmation. Contact us for current prices, availability and allergen information.</p></div>`;
let selectedCategory='All';
function renderMenu(){const q=document.querySelector('#menu-search').value.trim().toLowerCase();const filtered=dishes.filter(d=>(selectedCategory==='All'||d.category===selectedCategory)&&(d.name+' '+d.description+' '+d.category).toLowerCase().includes(q));document.querySelector('#menu-grid').innerHTML=filtered.map(dishCard).join('');document.querySelector('#empty-result').hidden=filtered.length>0;document.querySelector('#results-label').textContent=filtered.length+' '+(filtered.length===1?'dish':'dishes')+(selectedCategory==='All'?' across India':' · '+selectedCategory);document.querySelectorAll('.category').forEach(b=>b.setAttribute('aria-pressed',b.dataset.category===selectedCategory))}
document.querySelector('#menu-search').addEventListener('input',renderMenu);document.querySelectorAll('.category').forEach(b=>b.addEventListener('click',()=>{selectedCategory=b.dataset.category;renderMenu()}));document.querySelector('#reset-search').addEventListener('click',()=>{selectedCategory='All';document.querySelector('#menu-search').value='';renderMenu();document.querySelector('#menu-search').focus()});renderMenu();
function route(){const hash=location.hash||'#home';const isMenu=hash==='#menu';document.querySelector('#home-view').hidden=isMenu;document.querySelector('#menu-view').hidden=!isMenu;document.querySelector('#nav').classList.remove('open');document.querySelector('#nav-toggle').setAttribute('aria-expanded','false');document.querySelector('#nav-toggle').setAttribute('aria-label','Open navigation');document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.hash===hash));document.title=isMenu?'Menu | Akshar Pure Veg Restaurant Qatar':'Akshar Pure Veg Restaurant Qatar | Authentic Indian Vegetarian Food';requestAnimationFrame(()=>{if(isMenu||hash==='#home')window.scrollTo({top:0,behavior:'instant'});else document.querySelector(hash)?.scrollIntoView({behavior:'smooth'})})}window.addEventListener('hashchange',route);route();
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const body=`Name: ${f.get('name')}\nPhone: ${f.get('phone')}\nEmail: ${f.get('email')}\n\n${f.get('message')}`;const url='mailto:'+restaurant.email+'?subject='+encodeURIComponent('Website enquiry from '+f.get('name'))+'&body='+encodeURIComponent(body);window.location.href=url;document.querySelector('#form-status').textContent='Your email draft is ready. Send it from your email app. You can also reach us on WhatsApp.'});
const lightbox=document.querySelector('#lightbox');let galleryIndex=0;function showImage(i){galleryIndex=(i+gallery.length)%gallery.length;const g=gallery[galleryIndex];lightbox.querySelector('img').src='images/'+g.image+'.webp';lightbox.querySelector('img').alt=g.label;lightbox.querySelector('p').textContent=g.label+' · representative photography'}document.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{showImage(Number(b.dataset.gallery));lightbox.showModal();document.body.style.overflow='hidden'}));document.querySelector('.close-dialog').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('close',()=>document.body.style.overflow='');lightbox.addEventListener('click',e=>{if(e.target===lightbox){const r=lightbox.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)lightbox.close()}});document.querySelector('#prev-image').addEventListener('click',()=>showImage(galleryIndex-1));document.querySelector('#next-image').addEventListener('click',()=>showImage(galleryIndex+1));lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')showImage(galleryIndex-1);if(e.key==='ArrowRight')showImage(galleryIndex+1)});
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal');observer.unobserve(e.target)}})},{threshold:.06});document.querySelectorAll('.section-heading,.about-copy,.value,.why-item').forEach(el=>observer.observe(el));
const ld=document.createElement('script');ld.type='application/ld+json';ld.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Restaurant',name:restaurant.name,description:'Authentic pure vegetarian Indian food in Qatar.',servesCuisine:['Indian','Vegetarian'],telephone:restaurant.phone,email:restaurant.email,address:{'@type':'PostalAddress',addressLocality:'Al Wukair',addressCountry:'QA'},url:'https://akshar-pure-veg-qatar.aayushmistry72.chatgpt.site',hasMenu:'https://akshar-pure-veg-qatar.aayushmistry72.chatgpt.site/#menu'});document.head.appendChild(ld);
